name: Github Action Sharing - Greeting

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'
        required: true
        default: 'prod'


jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello Github Action!'