name: Github Action sharing - Environment 

on:
  push

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "${{ env.GREETING }} $FULL_NAME. Today is ${{ env.DAY_OF_WEEK }}"
        env:
          FULL_NAME: 'Hank YAO'
    env:
      GREETING: Hello

env:
  DAY_OF_WEEK: Monday