name: Github Action Sharing - Greeting

on:
  push

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'Hello Github Action!'

      - name: Print Ip Addr
        run: ip addr show