name: Github Action Sharing - Greeting

on:
  push

env:
  DAY_OF_WEEK: Monday

jobs:
  Greeting:
    runs-on: ubuntu-latest
    env:
      GREETING: Hello
    steps:
      - name: Say Hello
        run: echo '${{env.GREETING}} $FULL_NAME. Today is ${{env.DAY_OF_WEEK}}'
        env: 
          FULL_NAME: "Hank Yao"

      - name: Print Ip Addr
        run: ip addr show